# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = QtWidgetsApplication1
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"../../../../../Documents/glm/cmake/glm"
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(QtWidgetsApplication1.pri)
